# `RELIANCE - NSE Stock Data`

The file contains RELIANCE - NSE Stock Data from 1-Jan-16 to 6-May-21

The data can be used to forecast the stock prices of the future

Its a timeseries data from the national stock exchange of India

|| `Variable` | `Significance` |
| ------------- |:-------------:|:-------------:|
|1.|Symbol|Symbol of the listed stock on NSE|
|2.|Series|To which series does the stock belong (Equity, Options Future)|
|3.|Date|Date of the trade|
|4.|Prev Close|Previous day closing value of the stock|
|5.|Open Price|Current Day opening price of the stock|
|6.|High Price|Highest price touched by the stock in current day|
|7.|Low Price|lowest price touched by the stock in current day|
|8.|Last Price|The price at which last trade occured in current day|
|9.|Close Price|Current day closing price of the stock|
|10.|Average Price|Average price of the day|
|11.|Total Traded Quantity|Total number of stocks traded in current day|
|12.|Turnover||
|13.|No. of Trades|Current day's total number of trades|
|14.|Deliverabel Quantity|Current day deliveable quantity to the traders|
|15.|% Dly Qt to Traded Qty|`(Deliverable Quantity/Total Traded Quantity)*100`|

In [1]:
import pandas as pd

data_path="./raw-data/reliance/RILO - Copy.csv"
data=pd.read_csv(data_path)
data

,Symbol,Series,Date,Prev Close,Open Price,High Price,Low Price,Last Price,Close Price,Average Price,Total Traded Quantity,Turnover,No. of Trades,Deliverable Qty,% Dly Qt to Traded Qty
0,RELIANCE,EQ,1-Jan-16,1014.60,1009.80,1018.9,1008.20,1013.6,1015.35,1015.52,1238135,1.257353e+09,30701,529539,42.77
1,RELIANCE,EQ,4-Jan-16,1015.35,1005.00,1013.8,986.70,993.2,995.30,998.91,6896571,6.889070e+09,66235,4974602,72.13
2,RELIANCE,EQ,5-Jan-16,995.30,1000.30,1010.0,997.00,1005.0,1005.15,1003.41,3416459,3.428125e+09,59935,1987804,58.18
3,RELIANCE,EQ,6-Jan-16,1005.15,1007.60,1038.4,1000.40,1029.1,1032.20,1028.15,6116855,6.289073e+09,160947,2912662,47.62
4,RELIANCE,EQ,7-Jan-16,1032.20,1021.05,1028.0,1008.05,1018.9,1013.25,1016.73,4512219,4.587700e+09,105075,2474491,54.84
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1319,RELIANCE,EQ,30-Apr-21,2024.05,2008.50,2036.0,1987.55,1995.9,1994.50,2010.20,9150974,1.839532e+10,288687,3902504,42.65
1320,RELIANCE,EQ,3-May-21,1994.50,1966.00,1979.0,1943.10,1956.0,1959.05,1958.46,10909942,2.136664e+10,343806,3800598,34.84
1321,RELIANCE,EQ,4-May-21,1959.05,1950.00,1967.8,1911.00,1918.0,1916.60,1935.83,10083693,1.952033e+10,325798,4435071,43.98
1322,RELIANCE,EQ,5-May-21,1916.60,1923.35,1938.5,1908.05,1921.5,1920.10,1923.26,5719649,1.100036e+10,190990,1762417,30.81
1323,RELIANCE,EQ,6-May-21,1920.10,1921.85,1935.0,1906.60,1932.0,1931.00,1920.95,6749281,1.296502e+10,221666,2830835,41.94

In [3]:
data.columns=["_".join(column.lower().split()) for column in data.columns]
data.columns

Index(['symbol', 'series', 'date', 'prev_close', 'open_price', 'high_price',
       'low_price', 'last_price', 'close_price', 'average_price',
       'total_traded_quantity', 'turnover', 'no._of_trades', 'deliverable_qty',
       '%_dly_qt_to_traded_qty'],
      dtype='object')